version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gym_postgres
    restart: always
    environment:
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym
      POSTGRES_DB: gymdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
